config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  # get '/friends', to: "friends#index"
  # get '/friends/:id', to: "friends#show"
  root 'friends#index'

    get 'search', to: 'friends#search'


  resources :friends do
     get :autocomplete_friend_first_name, :on => :collection

  end


  resources :photos

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  #
  # delete 'friends/:id/delete' => 'friends#destroy', as: 'friends_delete'
  # get '/friends/:id/delete' => 'friends#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true

  after_create :send_welcome_message

  def send_welcome_message
    tst = WelcomeMessageWorker.perform_async(self.first_name)
    puts "tst", tst

  end

  def self.search(first_name)
    Friend.where('lower(first_name) LIKE ?',"%#{first_name}%")
  end


  def the_name
    # some complex calculation

    puts "I am your Friend #{self.first_name}!"
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
	  has_attached_file :image

	    # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	   validates_attachment :image, presence: true,
  content_type: { content_type: "image/jpeg" },
  size: { in: 0..500.kilobytes }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # autocomplete :friend, :first_name, :full => true

    before_action :force_json, only: :search
  autocomplete :friend, :first_name


  def index
    puts params
    @friends = Friend.search(params[:search])
    # render json: @friends.map(&:first_name)
    # @friends = Friend.all

  end

  def search
    q = params[:search].downcase
    @friend = Friend.where("first_name LIKE ? or last_name LIKE ?", "%#{q}%", "%#{q}%").limit(5)

  end

  def show
    @friend = Friend.find(params[:id])
  end

  def new
    @friend = Friend.new
  end

  def edit
    @friend = Friend.find(params[:id])
    puts @friend
  end


  def create
    @friend = Friend.new(friend_params)

    if @friend.save
      flash[:success] = "Woohoo!, Friend Added"
      redirect_to @friend
    else
      render :new
    end
  end


  def update
    @friend = Friend.find(params[:id])

    if @friend.update(friend_params)
      flash[:success] = "Woohoo!, Friend Details Edited"

      redirect_to @friend
    else
      render 'edit'
    end
  end


  def destroy
    print("aahgsjhaghg")
    @friend = Friend.find(params[:id])
    @friend.destroy
    params[:id] = nil

    flash[:alert] = "Alerting you the Friend has been deleted!"

    #
    #
    #
    # respond_to do |format|
    #   if @friend.destroy
    #     format.html { redirect_to friends_url }
    #     format.json { head :no_content }
    #   else
    #     format.html # do something here
    #     format.json { head :no_content }
    #   end
    # end

    redirect_to friends_path
  end


  private

  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :search)
  end

  def force_json
    request.format = :json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	#Index action, photos gets listed in the order at which they were created
 def index
  @photos = Photo.order('created_at')
 end

 #New action for creating a new photo
 def new
  @photo = Photo.new
 end

 #Create action ensures that submitted photo gets created if it meets the requirements
 def create
  @photo = Photo.new(photo_params)
  if @photo.save
   flash[:notice] = "Successfully added new photo!"
   redirect_to root_path
  else
   flash[:alert] = "Error adding new photo!"
   render :new
  end
 end

 def destroy
  @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

 private

 #Permitted parameters when creating a photo. This is used for security reasons.
 def photo_params
  params.require(:photo).permit(:title, :image)
 end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/friends/_form.html.erb
<%= form_with model: @friend do |form| %>


  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@friend.errors.count, "error") %> prohibited
        this Friend from being saved:
      </h2>
      <ul>
        <% @friend.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>


  <div>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %>
  </div>


  <div>
    <%= form.label :twitter %><br>
    <%= form.text_field :twitter %>
  </div>
  <div>
<%= form.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', friends_path, class: "btn btn-xs btn-primary" %>

app/views/friends/index.html.erb
<h1>Friends</h1>

<!--<input type="search" class="form-control" placeholder="Enter name..." id='tag-autocomplete'>-->


<%= form_tag(friends_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], id: 'tag-autocomplete' %>
    <%= submit_tag "Search" %>
<% end %>



<table class="table table-bordered">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Twitter</th>
    <th></th>


  </tr>

  <% @friends.each do |friend| %>
    <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td> <%= link_to 'Show', friend, class: "btn btn-xs btn-success" %>
           <%= link_to 'Edit', edit_friend_path(friend), class: "btn btn-xs btn-primary" %>
           <%= link_to 'Destroy', friend,
                      method: :delete,
                      data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>
      </td>

    </tr>
  <% end %>
</table>



<%= link_to 'New Friend', new_friend_path, class: "btn btn-xs btn-success" %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form'  %>

<br>
<%= link_to 'Back', friends_path, class: "btn btn-xs btn-primary" %>

app/views/friends/show.html.erb
<!--<div class="jumbotron jumbotron-fluid">-->
<!--  <div class="container">-->
<!--    <h1 class="display-4">Fluid jumbotron</h1>-->
<!--    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>-->
<!--  </div>-->
<!--</div>-->



<p><%= @friend.first_name %></p>

<p><%= @friend.last_name %></p>


<p><%= @friend.email %></p>
<p><%= @friend.phone %></p>
<p><%= @friend.twitter %></p>



<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-xs btn-primary" %>

<%= link_to 'Destroy', @friend,
                method: :delete,
                data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>

<%= link_to 'Back', friends_path, class: "btn btn-xs btn-success" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
<!--    <a class="navbar-brand" href="#">Friend APP</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
<!--          <a class="nav-link" href="#">Link</a>-->
          <%= link_to 'About', home_about_path, class:"nav-link" %>

                            


        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Images', photos_path,  class:"dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#index</h1>
<p>About</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  <title>Friends</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
<!--  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>
<body>

<%= render 'home/header' %>

<%= render 'shared/messages' %>



<div class="container">
  <br>
<%= yield %>
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>-->

<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
</body>
</html>

app/views/photos/index.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= link_to 'Add', new_photo_path, class: 'btn btn-danger' %>

<div class="media">
  <% @photos.each do |photo| %>
    <div class="media-left">
      <!-- Renders image -->
      <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>

            <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>

    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= photo.title %></h4>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
<!--   <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  # <% end %> -->


  <% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
 </div>
</div>